#!/usr/bin/perl
use strict;
use warnings;

my %media = (
    xegs => {window => '$8000', pages => 32},
    megamax => {window => '$8000', pages => 64},
    atarimax => {window => '$A000', pages => 32},
    megacart => {window => '$8000', pages => 64},
    sic => {window => '$8000', pages => 64},
    thecart => {window => '$A000', pages => 32},
    ram => {window => '$4000', pages => 64},
    emulator => {window => '$4000', pages => 128},
);

sub main {
    my $player = `cat player.asm.pl`;
    for my $media (sort keys %media) {
        my $cart = $media =~ /ram|emulator/ ? 0 : 1;
	for my $method (qw(pcm44 pcm4 pwm covox)) {
	    for my $channels (qw(stereo mono)) {
		for my $period (reverse qw(34 37 48 105 210)) {
                    my $fn = "player-$media-$method-$channels-$period.asm.pl";
                    open my $fh, ">$fn" or die "ERROR: Cannot open $fn: $!\n";
		    print $fh "\$media='$media'; \$$media=1; \$cart=$cart; \$$method=1; \$$channels=1; \$period=$period;";
                    for my $var (sort keys %{$media{$media}}) {
                        my $val = $media{$media}{$var};
                        if ($val =~ /\$/) {
                            print $fh " \$$var='$media{$media}{$var}';";
                        } else {
                            print $fh " \$$var=$media{$media}{$var};";
                        }
                    }
                    print $fh "\n";
                    print $fh $player;
                    close $fh;
                    my $asm = $fn;
                    $asm =~ s/\.pl$//;
                    my $lab = $fn;
                    $lab =~ s/\.asm\.pl$/.lab/;
                    my $lst = $fn;
                    $lst =~ s/\.asm\.pl$/.lst/;
                    warn "INFO: Assembling $asm...\n";
                    system "perl $fn > $asm";
                    system "xasm /t:$lab /l:$lst $asm";
		}
	    }
	}
    }
}

main();
