#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;
use MIME::Base64;
use JSON;

my %args;

sub usage {
    die "Usage: obx2json [player.obx]+\n";
}

sub parse_labels {
    my ($file) = @_;
    open my $fh, $file or die "ERROR: Cannot open $file: $!\n";
    my %labels;

    # xasm 3.1.0
    # Label table:
    #         D208 ALLPOT
    #         D201 AUDC1
    #         D203 AUDC2
    #         D205 AUDC3
    while (<$fh>) {
        if (/^ +(\S+)\s+(\S+)/) {
            my $value = hex($1);
            my $name = $2;
            # Exclude hardware labels
            if (not ($value >= 0xD000 and $value <= 0xD7FF)) {
                $labels{lc $2} = hex($1);
            }
        }
    }
    return \%labels;
}

sub parse_obx {
    my ($file) = @_;
    open my $fh, $file or die "ERROR: Cannot open $file: $!\n";
    read $fh, my $data, 1<<20;
    return encode_base64($data, "");
}

sub main {
    GetOptions(\%args,
    ) or usage();

    my %players;
    while (@ARGV) {
        my $obx = shift @ARGV;
        $obx =~ m{(.*/)?(\S+)\.obx} or die "ERROR: Expecting obx file: $obx\n";
        my $dir = $1;
        my $name = $2;
        my $lab = "$dir$name.lab";
        my $l = $players{$name}{labels} = parse_labels($lab);
        if (($l->{slow_cycles}//0) <= 5 and ($l->{fast_cycles}//0) <= 5) {
            $players{$name}{player} = parse_obx($obx);
        }
    }
    print JSON->new->utf8->canonical(1)->pretty(1)->encode(\%players);
}

main();
